const createEmojiOptions = (entries) =>
  entries.map(([symbol, label, keywords = ""]) => ({
    symbol,
    label,
    searchText: `${label} ${keywords}`.toLowerCase(),
  }));

const createRichOption = ({
  id,
  label,
  emoji,
  caption,
  accent,
  surface,
  secondary,
  keywords,
  motion = "float",
}) => ({
  id,
  label,
  emoji,
  caption,
  accent,
  surface,
  secondary,
  motion,
  searchText: `${label} ${caption} ${keywords}`.toLowerCase(),
});

export const emojiCategories = [
  {
    id: "smileys",
    label: "Smileys",
    options: createEmojiOptions([
      ["😀", "grinning face", "happy smile joy"],
      ["😃", "smiling face", "bright cheerful"],
      ["😄", "smile with eyes", "laugh friendly"],
      ["😁", "beaming grin", "teeth excited"],
      ["😆", "laughing face", "haha funny"],
      ["😂", "tears of joy", "lol laugh crying"],
      ["🤣", "rolling on the floor laughing", "rofl meme"],
      ["😊", "smiling blush", "kind sweet warm"],
      ["😍", "heart eyes", "love crush adore"],
      ["🥰", "smiling with hearts", "affection cozy"],
      ["😘", "kiss face", "flirty sweet"],
      ["😎", "cool face", "swagger chill"],
      ["🤩", "star struck", "wow amazed"],
      ["🥳", "party face", "celebrate birthday"],
      ["🤯", "mind blown", "shock wow"],
      ["😴", "sleepy face", "tired nap"],
      ["😭", "loudly crying", "sad tears"],
      ["😡", "pouting face", "angry upset"],
    ]),
  },
  {
    id: "people",
    label: "People",
    options: createEmojiOptions([
      ["👋", "waving hand", "hello hi bye"],
      ["🤝", "handshake", "deal agree team"],
      ["🙏", "folded hands", "thanks please prayer"],
      ["👍", "thumbs up", "approve yes"],
      ["👎", "thumbs down", "no dislike"],
      ["👏", "clapping hands", "applause nice"],
      ["🙌", "raised hands", "hooray celebrate"],
      ["💪", "flexed biceps", "strong gym power"],
      ["✌️", "victory hand", "peace win"],
      ["🤟", "love you gesture", "support"],
      ["🤌", "pinched fingers", "italian emphasis"],
      ["🫶", "heart hands", "care support"],
      ["🤗", "hugging face", "hug warm"],
      ["🤔", "thinking face", "hmm question"],
      ["🤭", "hand over mouth", "oops shy"],
      ["🫡", "saluting face", "respect noted"],
      ["🙋", "raising hand", "pick me answer"],
      ["🕺", "man dancing", "dance party"],
    ]),
  },
  {
    id: "nature",
    label: "Nature",
    options: createEmojiOptions([
      ["🌞", "sun with face", "sunshine bright"],
      ["🌈", "rainbow", "color happy weather"],
      ["⭐", "star", "night sparkle"],
      ["⚡", "lightning", "energy power"],
      ["🔥", "fire", "hot lit"],
      ["❄️", "snowflake", "winter cold"],
      ["🌊", "water wave", "ocean chill"],
      ["🌸", "cherry blossom", "flower spring"],
      ["🌻", "sunflower", "yellow bloom"],
      ["🍀", "four leaf clover", "luck"],
      ["🌴", "palm tree", "vacation beach"],
      ["🪴", "potted plant", "green cozy"],
      ["🐶", "dog face", "puppy pet"],
      ["🐱", "cat face", "kitty pet"],
      ["🦊", "fox", "clever animal"],
      ["🐼", "panda", "cute bamboo"],
      ["🦋", "butterfly", "soft pretty"],
      ["🐝", "bee", "buzz honey"],
    ]),
  },
  {
    id: "food",
    label: "Food",
    options: createEmojiOptions([
      ["🍕", "pizza", "slice cheesy"],
      ["🍔", "burger", "fast food"],
      ["🌮", "taco", "mexican food"],
      ["🍟", "fries", "snack"],
      ["🍿", "popcorn", "movie"],
      ["🍩", "doughnut", "sweet dessert"],
      ["🎂", "birthday cake", "party sweet"],
      ["🧁", "cupcake", "treat frosting"],
      ["🍫", "chocolate bar", "sweet cocoa"],
      ["🍓", "strawberry", "fruit berry"],
      ["🍉", "watermelon", "fruit summer"],
      ["🥑", "avocado", "healthy brunch"],
      ["🍜", "steaming bowl", "ramen noodles"],
      ["🍣", "sushi", "japanese food"],
      ["☕", "hot beverage", "coffee cafe"],
      ["🧋", "bubble tea", "boba drink"],
      ["🥤", "cup with straw", "soda drink"],
      ["🍹", "tropical drink", "mocktail vacation"],
    ]),
  },
  {
    id: "travel",
    label: "Travel",
    options: createEmojiOptions([
      ["🚗", "car", "road trip drive"],
      ["🚕", "taxi", "ride city"],
      ["🛵", "motor scooter", "fast ride"],
      ["🚲", "bicycle", "cycle ride"],
      ["✈️", "airplane", "flight travel"],
      ["🚀", "rocket", "launch space"],
      ["🛸", "flying saucer", "ufo alien"],
      ["🚄", "high speed train", "rail travel"],
      ["🚌", "bus", "commute city"],
      ["🗺️", "world map", "journey trip"],
      ["🏖️", "beach with umbrella", "holiday relax"],
      ["🏕️", "camping", "nature trip"],
      ["🏙️", "city skyline", "downtown"],
      ["🌋", "volcano", "adventure mountain"],
      ["🗽", "statue of liberty", "landmark usa"],
      ["🧭", "compass", "explore direction"],
      ["🎡", "ferris wheel", "funfair"],
      ["🎢", "roller coaster", "thrill theme park"],
    ]),
  },
  {
    id: "activities",
    label: "Activities",
    options: createEmojiOptions([
      ["⚽", "soccer ball", "football sport"],
      ["🏀", "basketball", "hoops game"],
      ["🏈", "american football", "touchdown sport"],
      ["🎾", "tennis", "racket sport"],
      ["🏸", "badminton", "shuttle sport"],
      ["🥊", "boxing glove", "fight punch"],
      ["🎯", "bullseye", "target focus"],
      ["🎮", "video game", "gaming console"],
      ["🧩", "puzzle piece", "brain teaser"],
      ["🎨", "artist palette", "paint creative"],
      ["🎧", "headphones", "music audio"],
      ["🎤", "microphone", "singing karaoke"],
      ["🎬", "clapper board", "film movie"],
      ["📚", "books", "study reading"],
      ["🛼", "roller skate", "fun retro"],
      ["🏆", "trophy", "winner champion"],
      ["🥇", "gold medal", "first place"],
      ["🎊", "confetti ball", "celebration"],
    ]),
  },
  {
    id: "objects",
    label: "Objects",
    options: createEmojiOptions([
      ["💡", "light bulb", "idea smart"],
      ["📱", "mobile phone", "call text"],
      ["💻", "laptop", "code work"],
      ["⌚", "watch", "time"],
      ["📷", "camera", "photo shoot"],
      ["🎁", "gift", "present surprise"],
      ["🛍️", "shopping bags", "buy mall"],
      ["🔒", "locked", "secure private"],
      ["🔑", "key", "unlock access"],
      ["🧸", "teddy bear", "cute soft"],
      ["🪩", "mirror ball", "dance disco"],
      ["🪄", "magic wand", "sparkle spell"],
      ["🕯️", "candle", "calm cozy"],
      ["💎", "gem stone", "shine luxury"],
      ["📦", "package", "delivery box"],
      ["🧠", "brain", "think smart"],
      ["📝", "memo", "note write"],
      ["📌", "pushpin", "important mark"],
    ]),
  },
  {
    id: "symbols",
    label: "Symbols",
    options: createEmojiOptions([
      ["❤️", "red heart", "love care"],
      ["🧡", "orange heart", "warm support"],
      ["💛", "yellow heart", "friendship bright"],
      ["💚", "green heart", "nature calm"],
      ["💙", "blue heart", "trust peace"],
      ["💜", "purple heart", "kindness style"],
      ["🖤", "black heart", "dark mood"],
      ["🤍", "white heart", "pure clean"],
      ["💯", "hundred points", "perfect"],
      ["✅", "check mark", "done approved"],
      ["❌", "cross mark", "stop no"],
      ["⚠️", "warning", "caution alert"],
      ["❓", "question mark", "ask doubt"],
      ["❗", "exclamation mark", "important wow"],
      ["➕", "plus sign", "add more"],
      ["➖", "minus sign", "less subtract"],
      ["♻️", "recycle", "green reuse"],
      ["🔔", "bell", "notify reminder"],
    ]),
  },
];

export const stickerOptions = [
  createRichOption({
    id: "confetti-pop",
    label: "Confetti Pop",
    emoji: "🎉",
    caption: "Big win energy",
    accent: "#f43f5e",
    surface: "#2b1220",
    secondary: "#f59e0b",
    keywords: "celebrate party confetti win yay",
  }),
  createRichOption({
    id: "heart-cloud",
    label: "Heart Cloud",
    emoji: "💖",
    caption: "Sending good vibes",
    accent: "#fb7185",
    surface: "#2b1424",
    secondary: "#c084fc",
    keywords: "love heart sweet adorable",
  }),
  createRichOption({
    id: "rocket-mode",
    label: "Rocket Mode",
    emoji: "🚀",
    caption: "Locked in and moving",
    accent: "#60a5fa",
    surface: "#10213b",
    secondary: "#22d3ee",
    keywords: "launch hustle growth ship",
  }),
  createRichOption({
    id: "thumbs-up",
    label: "Thumbs Up",
    emoji: "👍",
    caption: "Approved",
    accent: "#34d399",
    surface: "#10241f",
    secondary: "#10b981",
    keywords: "yes okay cool done",
  }),
  createRichOption({
    id: "mind-blown",
    label: "Mind Blown",
    emoji: "🤯",
    caption: "That was wild",
    accent: "#f97316",
    surface: "#2b1910",
    secondary: "#facc15",
    keywords: "shock wow crazy insane",
  }),
  createRichOption({
    id: "cozy-coffee",
    label: "Cozy Coffee",
    emoji: "☕",
    caption: "Slow and steady",
    accent: "#fb923c",
    surface: "#26180f",
    secondary: "#fdba74",
    keywords: "coffee break chill relax",
  }),
  createRichOption({
    id: "sunny-smile",
    label: "Sunny Smile",
    emoji: "🌞",
    caption: "Bringing bright energy",
    accent: "#facc15",
    surface: "#2c210b",
    secondary: "#fb7185",
    keywords: "happy sunshine positive",
  }),
  createRichOption({
    id: "crown-moment",
    label: "Crown Moment",
    emoji: "👑",
    caption: "Main character mood",
    accent: "#eab308",
    surface: "#2a230d",
    secondary: "#f59e0b",
    keywords: "royal queen king slay",
  }),
  createRichOption({
    id: "clap-burst",
    label: "Clap Burst",
    emoji: "👏",
    caption: "That deserves applause",
    accent: "#38bdf8",
    surface: "#10212a",
    secondary: "#a855f7",
    keywords: "clap applause nice work",
  }),
  createRichOption({
    id: "cool-cat",
    label: "Cool Cat",
    emoji: "😎",
    caption: "Smooth delivery",
    accent: "#8b5cf6",
    surface: "#1a1533",
    secondary: "#06b6d4",
    keywords: "cool style vibe chill",
  }),
  createRichOption({
    id: "green-light",
    label: "Green Light",
    emoji: "✅",
    caption: "We are good to go",
    accent: "#22c55e",
    surface: "#122516",
    secondary: "#4ade80",
    keywords: "approved yes ready done",
  }),
  createRichOption({
    id: "hug-bundle",
    label: "Hug Bundle",
    emoji: "🤗",
    caption: "A little support",
    accent: "#f472b6",
    surface: "#301322",
    secondary: "#c084fc",
    keywords: "hug comfort care support",
  }),
];

export const gifOptions = [
  createRichOption({
    id: "party-loop",
    label: "Party Loop",
    emoji: "🥳",
    caption: "Instant celebration",
    accent: "#f97316",
    surface: "#2d180d",
    secondary: "#ec4899",
    keywords: "party celebrate birthday hype",
    motion: "pulse",
  }),
  createRichOption({
    id: "happy-dance",
    label: "Happy Dance",
    emoji: "💃",
    caption: "Energy all the way up",
    accent: "#ec4899",
    surface: "#2d1324",
    secondary: "#f59e0b",
    keywords: "dance groove excited joy",
    motion: "bounce",
  }),
  createRichOption({
    id: "big-laugh",
    label: "Big Laugh",
    emoji: "😂",
    caption: "That sent me",
    accent: "#60a5fa",
    surface: "#10223a",
    secondary: "#22d3ee",
    keywords: "lol funny laugh meme",
    motion: "float",
  }),
  createRichOption({
    id: "clap-loop",
    label: "Clap Loop",
    emoji: "👏",
    caption: "Round of applause",
    accent: "#38bdf8",
    surface: "#10212a",
    secondary: "#a78bfa",
    keywords: "clap appreciate nice work",
    motion: "ripple",
  }),
  createRichOption({
    id: "heart-wave",
    label: "Heart Wave",
    emoji: "😍",
    caption: "Pure admiration",
    accent: "#fb7185",
    surface: "#321522",
    secondary: "#f472b6",
    keywords: "love adore heart crush",
    motion: "pulse",
  }),
  createRichOption({
    id: "fire-mode",
    label: "Fire Mode",
    emoji: "🔥",
    caption: "That is hot",
    accent: "#f97316",
    surface: "#31180c",
    secondary: "#facc15",
    keywords: "fire lit hype trending",
    motion: "spark",
  }),
  createRichOption({
    id: "wow-burst",
    label: "Wow Burst",
    emoji: "😮",
    caption: "No way",
    accent: "#818cf8",
    surface: "#19173c",
    secondary: "#38bdf8",
    keywords: "wow shock surprise amazed",
    motion: "pulse",
  }),
  createRichOption({
    id: "success-rocket",
    label: "Success Rocket",
    emoji: "🚀",
    caption: "Momentum unlocked",
    accent: "#34d399",
    surface: "#10281f",
    secondary: "#60a5fa",
    keywords: "success growth ship launch",
    motion: "float",
  }),
  createRichOption({
    id: "cozy-loop",
    label: "Cozy Loop",
    emoji: "☕",
    caption: "Caffeine refuel",
    accent: "#fb923c",
    surface: "#2a180d",
    secondary: "#f59e0b",
    keywords: "coffee chill relax morning",
    motion: "ripple",
  }),
  createRichOption({
    id: "victory-vibe",
    label: "Victory Vibe",
    emoji: "✌️",
    caption: "We did it",
    accent: "#22c55e",
    surface: "#122516",
    secondary: "#38bdf8",
    keywords: "victory win peace celebrate",
    motion: "bounce",
  }),
  createRichOption({
    id: "mind-bend",
    label: "Mind Bend",
    emoji: "🌀",
    caption: "Plot twist energy",
    accent: "#a855f7",
    surface: "#1f1231",
    secondary: "#ec4899",
    keywords: "mind blown twist spin wow",
    motion: "spin",
  }),
  createRichOption({
    id: "sunbeam-loop",
    label: "Sunbeam Loop",
    emoji: "✨",
    caption: "Soft sparkle moment",
    accent: "#facc15",
    surface: "#2e250d",
    secondary: "#f59e0b",
    keywords: "sparkle shine glow happy",
    motion: "spark",
  }),
];

export const stickerOptionsById = Object.fromEntries(
  stickerOptions.map((option) => [option.id, option])
);

export const gifOptionsById = Object.fromEntries(
  gifOptions.map((option) => [option.id, option])
);
